In [2]:
import numpy as np # linear algebra
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler, RobustScaler

In [54]:
seq_data = [1,2,3,4,5,6]
non_seq_data = [1,3,4,2,4,6,7,8,3,9,7,5,6,9,3,7]

In [55]:
seq_test = np.array(seq_data)
non_seq_test = np.array(non_seq_data)
seq_test = seq_test.reshape(-1,1)
non_seq_test = non_seq_test.reshape(-1,1)

# Normalize every samples

In [65]:
t = 3
def make_samples(sc, data):
    x_test = []
    y_test = []
    l = len(data)
    for i in range(t, l):
        x = data[i-t:i,0]
        y = data[i,0]
        x_y =[i for i in x]
        x_y.append(y)
        x_y = np.array(x_y)
        x_y= x_y.reshape(-1,1)
        
        sc.fit(x_y)
        x = x.reshape(-1,1)
        y = y.reshape(-1,1)
        x_test.append(sc.transform(x))
        y_test.append(sc.transform(y))
    return x_test, y_test

# MinMaxScaler

## Sequentially values

In [66]:
sc = MinMaxScaler(feature_range=(0,1))
x_test, y_test = make_samples(sc, seq_test)
x_test, y_test = np.array(x_test), np.array(y_test)

In [67]:
x_test

array([[[0.        ],
        [0.33333333],
        [0.66666667]],

       [[0.        ],
        [0.33333333],
        [0.66666667]],

       [[0.        ],
        [0.33333333],
        [0.66666667]]])

## Non sequentially values

In [68]:
sc = MinMaxScaler(feature_range=(0,1))
x_test, y_test = make_samples(sc, non_seq_test)
x_test, y_test = np.array(x_test), np.array(y_test)

In [69]:
x_test

array([[[0.        ],
        [0.66666667],
        [1.        ]],

       [[0.5       ],
        [1.        ],
        [0.        ]],

       [[0.5       ],
        [0.        ],
        [0.5       ]],

       [[0.        ],
        [0.4       ],
        [0.8       ]],

       [[0.        ],
        [0.5       ],
        [0.75      ]],

       [[0.6       ],
        [0.8       ],
        [1.        ]],

       [[0.66666667],
        [0.83333333],
        [0.        ]],

       [[0.83333333],
        [0.        ],
        [1.        ]],

       [[0.        ],
        [1.        ],
        [0.66666667]],

       [[1.        ],
        [0.5       ],
        [0.        ]],

       [[0.5       ],
        [0.        ],
        [0.25      ]],

       [[0.33333333],
        [0.5       ],
        [1.        ]],

       [[0.5       ],
        [1.        ],
        [0.        ]]])

# StandardScaler

In [59]:
sc = StandardScaler()
x_test, y_test = make_samples(sc, seq_test)
x_test, y_test = np.array(x_test), np.array(y_test)

In [60]:
x_test

array([[[-1.34164079],
        [-0.4472136 ],
        [ 0.4472136 ]],

       [[-1.34164079],
        [-0.4472136 ],
        [ 0.4472136 ]],

       [[-1.34164079],
        [-0.4472136 ],
        [ 0.4472136 ]]])

# RobustScaler

In [61]:
sc = RobustScaler()
x_test, y_test = make_samples(sc, seq_test)
x_test, y_test = np.array(x_test), np.array(y_test)

In [62]:
x_test

array([[[-1.        ],
        [-0.33333333],
        [ 0.33333333]],

       [[-1.        ],
        [-0.33333333],
        [ 0.33333333]],

       [[-1.        ],
        [-0.33333333],
        [ 0.33333333]]])

# MaxAbsScaler

In [63]:
sc = MaxAbsScaler()
x_test, y_test = make_samples(sc, seq_test)
x_test, y_test = np.array(x_test), np.array(y_test)

In [64]:
x_test

array([[[0.25      ],
        [0.5       ],
        [0.75      ]],

       [[0.4       ],
        [0.6       ],
        [0.8       ]],

       [[0.5       ],
        [0.66666667],
        [0.83333333]]])